// src/app/layout.tsx
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { LenisProvider } from "@/lib/lenis";
import { LanguageProvider } from "@/contexts/LanguageContext"; // <-- THÊM DÒNG NÀY

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Portfolio của Tùng Lê",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="!scroll-smooth">
      <body className={inter.className}>
        {/* BỌC LanguageProvider BÊN NGOÀI */}
        <LanguageProvider>
          <LenisProvider>{children}</LenisProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}